/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author usuario
 */
public class ini_secion extends javax.swing.JFrame {

    /**
     * Creates new form ini_secion
     */
    public ini_secion() {
        initComponents();
    }

    public JButton getBtingresar1() {
        return btingresar1;
    }

    public void setBtingresar1(JButton btingresar1) {
        this.btingresar1 = btingresar1;
    }

    public JPasswordField getJpcontra() {
        return jpcontra;
    }

    public void setJpcontra(JPasswordField jpcontra) {
        this.jpcontra = jpcontra;
    }

    public JButton getOjitomostrar() {
        return ojitomostrar;
    }

    public void setOjitomostrar(JButton ojitomostrar) {
        this.ojitomostrar = ojitomostrar;
    }

    public JTextField getTxtingreseusuario() {
        return txtingreseusuario;
    }

    public void setTxtingreseusuario(JTextField txtingreseusuario) {
        this.txtingreseusuario = txtingreseusuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lbliniciar1 = new javax.swing.JLabel();
        lblingrese1 = new javax.swing.JLabel();
        txtingreseusuario = new javax.swing.JTextField();
        lblclave1 = new javax.swing.JLabel();
        btingresar1 = new javax.swing.JButton();
        ojitomostrar = new javax.swing.JButton();
        lblbotonusu = new javax.swing.JLabel();
        jpcontra = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        lbliniciar1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbliniciar1.setText("Iniciar Sesión");

        lblingrese1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblingrese1.setText("Ingrese Usuario");

        lblclave1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblclave1.setText("Ingrese Clave");

        btingresar1.setText("Ingresar");

        ojitomostrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\usuario\\OneDrive\\Documentos\\NetBeansProjects\\tienda_con\\src\\main\\resources\\img\\Ojo-Abierto.png")); // NOI18N

        lblbotonusu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N

        jpcontra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpcontraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblingrese1)
                    .addComponent(lblclave1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtingreseusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpcontra, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ojitomostrar)
                            .addComponent(lblbotonusu)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbliniciar1)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btingresar1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbliniciar1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblingrese1)
                            .addComponent(txtingreseusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblbotonusu))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(lblclave1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jpcontra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(ojitomostrar))
                .addGap(46, 46, 46)
                .addComponent(btingresar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpcontraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpcontraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpcontraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btingresar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jpcontra;
    private javax.swing.JLabel lblbotonusu;
    private javax.swing.JLabel lblclave1;
    private javax.swing.JLabel lblingrese1;
    private javax.swing.JLabel lbliniciar1;
    private javax.swing.JButton ojitomostrar;
    private javax.swing.JTextField txtingreseusuario;
    // End of variables declaration//GEN-END:variables
}
