/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author usuario
 */
public class NuevaFactura extends javax.swing.JFrame {

    /**
     * Creates new form NuevaFactura
     */
    public NuevaFactura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblnuevafactura = new javax.swing.JLabel();
        lbltipopa = new javax.swing.JLabel();
        cbxtipopago = new javax.swing.JComboBox<>();
        lblcedulafac = new javax.swing.JLabel();
        txtcedufac = new javax.swing.JTextField();
        lblidusuarioo = new javax.swing.JLabel();
        txtidusu = new javax.swing.JTextField();
        btguarnufac = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblnuevafactura.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblnuevafactura.setText("NUEVA FACTURA");

        lbltipopa.setText("Tipo de pago:");

        cbxtipopago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione....", "Efectivo", "Tarjeta ", "Transaccion " }));

        lblcedulafac.setText("Cedula:");

        lblidusuarioo.setText("Id Usuario");

        btguarnufac.setText("Guardar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(lblnuevafactura))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbltipopa)
                            .addComponent(lblcedulafac)
                            .addComponent(lblidusuarioo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxtipopago, 0, 235, Short.MAX_VALUE)
                            .addComponent(txtcedufac)
                            .addComponent(txtidusu)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(btguarnufac)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblnuevafactura)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltipopa)
                    .addComponent(cbxtipopago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcedulafac)
                    .addComponent(txtcedufac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblidusuarioo)
                    .addComponent(txtidusu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(btguarnufac)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btguarnufac;
    private javax.swing.JComboBox<String> cbxtipopago;
    private javax.swing.JLabel lblcedulafac;
    private javax.swing.JLabel lblidusuarioo;
    private javax.swing.JLabel lblnuevafactura;
    private javax.swing.JLabel lbltipopa;
    private javax.swing.JTextField txtcedufac;
    private javax.swing.JTextField txtidusu;
    // End of variables declaration//GEN-END:variables
}
