/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author usuario
 */
public class NuevoProveedor extends javax.swing.JFrame {

  
    public NuevoProveedor() {
        initComponents();
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JComboBox<String> getCbxsexoo() {
        return cbxsexoo;
    }

    public void setCbxsexoo(JComboBox<String> cbxsexoo) {
        this.cbxsexoo = cbxsexoo;
    }

    public JComboBox<String> getCbxtipodocumento() {
        return cbxtipodocumento;
    }

    public void setCbxtipodocumento(JComboBox<String> cbxtipodocumento) {
        this.cbxtipodocumento = cbxtipodocumento;
    }

    public JComboBox<String> getCbxtipopersona() {
        return cbxtipopersona;
    }

    public void setCbxtipopersona(JComboBox<String> cbxtipopersona) {
        this.cbxtipopersona = cbxtipopersona;
    }

    public JDateChooser getjDateChooser1() {
        return jDateChooser1;
    }

    public void setjDateChooser1(JDateChooser jDateChooser1) {
        this.jDateChooser1 = jDateChooser1;
    }

    public JTextField getTxtcorreoo() {
        return txtcorreoo;
    }

    public void setTxtcorreoo(JTextField txtcorreoo) {
        this.txtcorreoo = txtcorreoo;
    }

    public JTextField getTxtdireccion() {
        return txtdireccion;
    }

    public void setTxtdireccion(JTextField txtdireccion) {
        this.txtdireccion = txtdireccion;
    }

    public JTextField getTxtnombree() {
        return txtnombree;
    }

    public void setTxtnombree(JTextField txtnombree) {
        this.txtnombree = txtnombree;
    }

    public JTextField getTxtproductos() {
        return txtproductos;
    }

    public void setTxtproductos(JTextField txtproductos) {
        this.txtproductos = txtproductos;
    }

    public JTextField getTxttelefonoo() {
        return txttelefonoo;
    }

    public void setTxttelefonoo(JTextField txttelefonoo) {
        this.txttelefonoo = txttelefonoo;
    }

    public JButton getBtcancelarpro() {
        return btcancelarpro;
    }

    public void setBtcancelarpro(JButton btcancelarpro) {
        this.btcancelarpro = btcancelarpro;
    }

    public JButton getBtguardarpro() {
        return btguardarpro;
    }

    public void setBtguardarpro(JButton btguardarpro) {
        this.btguardarpro = btguardarpro;
    }

   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        lbltipodocumento = new javax.swing.JLabel();
        cbxtipodocumento = new javax.swing.JComboBox<>();
        lblsexoo = new javax.swing.JLabel();
        cbxtipopersona = new javax.swing.JComboBox<>();
        cbxsexoo = new javax.swing.JComboBox<>();
        txtnombree = new javax.swing.JTextField();
        lblnombree = new javax.swing.JLabel();
        txtcorreoo = new javax.swing.JTextField();
        lblcorreoo = new javax.swing.JLabel();
        txttelefonoo = new javax.swing.JTextField();
        lbltelefonoo = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        lbldireccionn = new javax.swing.JLabel();
        txtproductos = new javax.swing.JTextField();
        lblproductos = new javax.swing.JLabel();
        btguardarpro = new javax.swing.JButton();
        lbltipodepersona = new javax.swing.JLabel();
        btcancelarpro = new javax.swing.JButton();
        lblfechadenacimientoo = new javax.swing.JLabel();
        lblnuevoproveedor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbltipodocumento.setText("Tipo De Documento");

        cbxtipodocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione....", "Cedula de ciudadania", "Nit", "Tarjeta de identidad", "Pasaporte" }));
        cbxtipodocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxtipodocumentoActionPerformed(evt);
            }
        });

        lblsexoo.setText("Sexo:");

        cbxtipopersona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Persona juridica", "Persona natural" }));

        lblnombree.setText("Nombre:");

        lblcorreoo.setText("Correo");

        lbltelefonoo.setText("Telefono:");

        lbldireccionn.setText("Direcccion:");

        lblproductos.setText("Productos:");

        btguardarpro.setText("Guardar");

        lbltipodepersona.setText("Tipo De Persona");

        btcancelarpro.setText("Cancelar");

        lblfechadenacimientoo.setText("Fecha De Nacimiento");

        lblnuevoproveedor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblnuevoproveedor.setText("NUEVO PROVEEDOR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblfechadenacimientoo)
                            .addComponent(lbltipodepersona)
                            .addComponent(lblproductos)
                            .addComponent(lbldireccionn)
                            .addComponent(lbltelefonoo)
                            .addComponent(lblcorreoo))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcorreoo)
                                    .addComponent(txttelefonoo)
                                    .addComponent(txtdireccion)
                                    .addComponent(cbxtipopersona, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtproductos)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbltipodocumento)
                            .addComponent(lblsexoo)
                            .addComponent(lblnombree))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxsexoo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxtipodocumento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtnombree, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblnuevoproveedor)
                .addGap(81, 81, 81))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(btguardarpro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btcancelarpro)
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblnuevoproveedor)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltipodocumento)
                    .addComponent(cbxtipodocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblsexoo)
                    .addComponent(cbxsexoo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblnombree)
                            .addComponent(txtnombree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblcorreoo)
                            .addComponent(txtcorreoo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbltelefonoo)
                            .addComponent(txttelefonoo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbldireccionn)
                            .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblproductos)
                            .addComponent(txtproductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbltipodepersona)
                            .addComponent(cbxtipopersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblfechadenacimientoo))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btguardarpro)
                    .addComponent(btcancelarpro))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxtipodocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxtipodocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxtipodocumentoActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcancelarpro;
    private javax.swing.JButton btguardarpro;
    private javax.swing.JComboBox<String> cbxsexoo;
    private javax.swing.JComboBox<String> cbxtipodocumento;
    private javax.swing.JComboBox<String> cbxtipopersona;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblcorreoo;
    private javax.swing.JLabel lbldireccionn;
    private javax.swing.JLabel lblfechadenacimientoo;
    private javax.swing.JLabel lblnombree;
    private javax.swing.JLabel lblnuevoproveedor;
    private javax.swing.JLabel lblproductos;
    private javax.swing.JLabel lblsexoo;
    private javax.swing.JLabel lbltelefonoo;
    private javax.swing.JLabel lbltipodepersona;
    private javax.swing.JLabel lbltipodocumento;
    private javax.swing.JTextField txtcorreoo;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtnombree;
    private javax.swing.JTextField txtproductos;
    private javax.swing.JTextField txttelefonoo;
    // End of variables declaration//GEN-END:variables
}
