/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;

/**
 *
 * @author usuario
 */
public class Ver_Detalle_Venta extends javax.swing.JFrame {

    /**
     * Creates new form Ver_Detalle_Venta
     */
    public Ver_Detalle_Venta() {
        initComponents();
    }

    public JTable getjTabledetalleven() {
        return jTabledetalleven;
    }

    public void setjTabledetalleven(JTable jTabledetalleven) {
        this.jTabledetalleven = jTabledetalleven;
    }

   

    public JLabel getLbltextocompro() {
        return lbltextocompro;
    }

    public void setLbltextocompro(JLabel lbltextocompro) {
        this.lbltextocompro = lbltextocompro;
    }

    public JLabel getLbltextofecha() {
        return lbltextofecha;
    }

    public void setLbltextofecha(JLabel lbltextofecha) {
        this.lbltextofecha = lbltextofecha;
    }

    public JLabel getLbltextoimpu() {
        return lbltextoimpu;
    }

    public void setLbltextoimpu(JLabel lbltextoimpu) {
        this.lbltextoimpu = lbltextoimpu;
    }

    public JLabel getLbltextotipopa() {
        return lbltextotipopa;
    }

    public void setLbltextotipopa(JLabel lbltextotipopa) {
        this.lbltextotipopa = lbltextotipopa;
    }

    public JLabel getLbltextousuario() {
        return lbltextousuario;
    }

    public void setLbltextousuario(JLabel lbltextousuario) {
        this.lbltextousuario = lbltextousuario;
    }

    public JLabel getLbltextovalorpagar() {
        return lbltextovalorpagar;
    }

    public void setLbltextovalorpagar(JLabel lbltextovalorpagar) {
        this.lbltextovalorpagar = lbltextovalorpagar;
    }

    public JLabel getLblclientetexto() {
        return lblclientetexto;
    }

    public void setLblclientetexto(JLabel lblclientetexto) {
        this.lblclientetexto = lblclientetexto;
    }

    public JLabel getLblfacturatextoo() {
        return lblfacturatextoo;
    }

    public void setLblfacturatextoo(JLabel lblfacturatextoo) {
        this.lblfacturatextoo = lblfacturatextoo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbldetalleventa = new javax.swing.JLabel();
        lblfactura = new javax.swing.JLabel();
        lblfacturatextoo = new javax.swing.JLabel();
        lblcliente = new javax.swing.JLabel();
        lblclientetexto = new javax.swing.JLabel();
        lbltipodepago = new javax.swing.JLabel();
        lbltextotipopa = new javax.swing.JLabel();
        lblfecha = new javax.swing.JLabel();
        lbltextofecha = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        lbltextousuario = new javax.swing.JLabel();
        lblcomprobante = new javax.swing.JLabel();
        lbltextocompro = new javax.swing.JLabel();
        lblimpuesto = new javax.swing.JLabel();
        lblvalorapagar = new javax.swing.JLabel();
        lbltextoimpu = new javax.swing.JLabel();
        lbltextovalorpagar = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTabledetalleven = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbldetalleventa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbldetalleventa.setText("Detalle Venta");

        lblfactura.setText("Factura");

        lblfacturatextoo.setText("jLabel1");

        lblcliente.setText("Cliente");

        lblclientetexto.setText("jLabel2");

        lbltipodepago.setText("Tipo De Pago");

        lbltextotipopa.setText("jLabel3");

        lblfecha.setText("Fecha");

        lbltextofecha.setText("jLabel4");

        lblusuario.setText("Usuario");

        lbltextousuario.setText("jLabel6");

        lblcomprobante.setText("Comprobante");

        lbltextocompro.setText("jLabel8");

        lblimpuesto.setText("Impuesto");

        lblvalorapagar.setText("Valor A Pagar");

        lbltextoimpu.setText("jLabel3");

        lbltextovalorpagar.setText("jLabel4");

        jTabledetalleven.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTabledetalleven);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblimpuesto)
                            .addComponent(lblvalorapagar))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbltextovalorpagar)
                            .addComponent(lbltextoimpu))
                        .addGap(74, 74, 74))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblcliente)
                                    .addComponent(lblfactura)
                                    .addComponent(lbltipodepago))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblclientetexto)
                                    .addComponent(lblfacturatextoo)
                                    .addComponent(lbltextotipopa))
                                .addGap(199, 199, 199)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbldetalleventa, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblusuario)
                                            .addComponent(lblcomprobante))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addComponent(lbltextocompro))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addComponent(lbltextousuario)))))
                                .addGap(60, 60, 60)
                                .addComponent(lblfecha)
                                .addGap(30, 30, 30)
                                .addComponent(lbltextofecha))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 902, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(26, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbldetalleventa)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfactura)
                    .addComponent(lblfacturatextoo)
                    .addComponent(lblfecha)
                    .addComponent(lbltextofecha))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblcliente)
                            .addComponent(lblclientetexto)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblusuario)
                            .addComponent(lbltextousuario))))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltipodepago)
                    .addComponent(lbltextotipopa)
                    .addComponent(lblcomprobante)
                    .addComponent(lbltextocompro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblimpuesto)
                    .addComponent(lbltextoimpu))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblvalorapagar)
                    .addComponent(lbltextovalorpagar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTabledetalleven;
    private javax.swing.JLabel lblcliente;
    private javax.swing.JLabel lblclientetexto;
    private javax.swing.JLabel lblcomprobante;
    private javax.swing.JLabel lbldetalleventa;
    private javax.swing.JLabel lblfactura;
    private javax.swing.JLabel lblfacturatextoo;
    private javax.swing.JLabel lblfecha;
    private javax.swing.JLabel lblimpuesto;
    private javax.swing.JLabel lbltextocompro;
    private javax.swing.JLabel lbltextofecha;
    private javax.swing.JLabel lbltextoimpu;
    private javax.swing.JLabel lbltextotipopa;
    private javax.swing.JLabel lbltextousuario;
    private javax.swing.JLabel lbltextovalorpagar;
    private javax.swing.JLabel lbltipodepago;
    private javax.swing.JLabel lblusuario;
    private javax.swing.JLabel lblvalorapagar;
    // End of variables declaration//GEN-END:variables
}
